create_clock -period 10.000 -name clk -waveform {0.000 5.000} -add [get_ports clk]

set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property PACKAGE_PIN T18 [get_ports PB_Start]
set_property IOSTANDARD LVCMOS18 [get_ports PB_Start]
set_property PACKAGE_PIN R16 [get_ports PB_Rst]
set_property IOSTANDARD LVCMOS18 [get_ports PB_Rst]
set_property PACKAGE_PIN U14 [get_ports {LEDs[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[7]}]
set_property PACKAGE_PIN U19 [get_ports {LEDs[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[6]}]
set_property PACKAGE_PIN W22 [get_ports {LEDs[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[5]}]
set_property PACKAGE_PIN V22 [get_ports {LEDs[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN U21 [get_ports {LEDs[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN U22 [get_ports {LEDs[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN T21 [get_ports {LEDs[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN T22 [get_ports {LEDs[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[0]}]

